version: '3'
services:
  minio:
    image: quay.io/minio/minio
    restart: always
    volumes:
      - minio:/data
    environment:
      - MINIO_ACCESS_KEY=minio
      - MINIO_SECRET_KEY=miniosecret
    ports:
      - "9000:9000"
      - "9001:9001"    

volumes:
  minio:
    driver: local
  db:
    driver: local